default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  schema_search_path: public
  username: superbowlsquares
  password: superbowlsquares
  host: localhost
  port: 5432

development:
  <<: *default
  database: superbowlsquares_development

test:
  <<: *default
  database: superbowlsquares_development

production:
  url: <%= ENV.fetch("DATABASE_URL") %>
